aldeotaclube/urls.py
from django.contrib import admin
from django.urls import path, include
from home import urls as home_urls
from noticias import urls as noticias_urls
from atletas import urls as atletas_urls
from artilharia import urls as artilharia_urls
from jogos import urls as jogos_urls
from .views import sobre, contato
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(home_urls)),
    path('sobre/', sobre, name='sobre'),
    path('noticias/', include(noticias_urls)),
    path('atletas/', include(atletas_urls)),
    path('artilharia/', include(artilharia_urls)),
    path('jogos/', include(jogos_urls)),
    path('contato/', contato, name='contato'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artilharia/urls.py
from django.urls import path
from .views import artilharia

urlpatterns = [
    path('', artilharia, name='artilharia'),
]

atletas/urls.py
from django.urls import path
from .views import atletas, detalhes

app_name = 'atletas'

urlpatterns = [
    path('', atletas, name='atletas'),
    path('<slug:slug>', detalhes, name='detalhes'),
]

home/urls.py
from django.urls import path
from .views import home

urlpatterns = [
    path('', home, name='home'),
]

jogos/urls.py
from django.urls import path
from .views import jogos

urlpatterns = [
    path('', jogos, name='jogos'),
]

noticias/urls.py
from django.urls import path
from .views import noticias, detalhes

app_name = 'noticias'

urlpatterns = [
    path('', noticias, name='noticias'),
    path('<slug:slug>', detalhes, name='detalhes'),
]

artilharia/models.py
from django.db import models

# Create your models here.

atletas/models.py
from django.db import models

class Atleta(models.Model):
    nome = models.CharField(max_length=50)
    sobrenome = models.CharField(max_length=50)
    apelido = models.CharField(max_length=50)
    idade = models.IntegerField()
    data_nascimento = models.DateField()
    local_nascimento = models.CharField(max_length=50)
    descricao = models.TextField()
    imagem = models.ImageField(upload_to='atletas', null=True, blank=True)
    slug = models.SlugField()

    def __str__(self):
        return self.nome + " " + self.sobrenome

jogos/models.py
from django.db import models

class Jogo(models.Model):
    adversario = models.CharField(max_length=50)
    data = models.DateField()
    local = models.CharField(max_length=50)
    arbitragem = models.CharField(max_length=80, null=True, blank=True)
    escudo_adversario = models.ImageField(default="comuns/sem_escudo.png", upload_to='jogos', null=True, blank=True)
    placar_aldeota = models.IntegerField(null=True, blank=True)
    placar_adversario = models.IntegerField(null=True, blank=True)
    resumo = models.TextField(null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.adversario

    class Meta:
        verbose_name = "Jogo"
        verbose_name_plural = "Jogos"

noticias/models.py
from django.db import models

class Noticia(models.Model):
    titulo = models.CharField(max_length=200)
    data = models.DateField()
    conteudo = models.TextField()
    imagem = models.ImageField(default='comuns/default.jpg', upload_to='noticias', null=True, blank=True)
    slug = models.SlugField()

    def __str__(self):
        return self.titulo

    def snippet(self):
        return self.conteudo[:50] + '...'

    def snippet_noticia(self):
        return self.conteudo[:150] + '...'

    class Meta:
        verbose_name = "Notícia"
        verbose_name_plural = "Notícias"

aldeotaclube/forms.py
from django import forms

class ContactForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    conteudo = forms.CharField(required=True, widget=forms.Textarea)

aldeotaclube/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from jogos.models import Jogo

from .forms import ContactForm

def sobre(request):
    jogos = Jogo.objects.order_by('-data')[:1]
    return render(request, 'sobre.html', {'jogos' : jogos})

def contato(request):
    form = ContactForm(request.POST)
    jogos = Jogo.objects.order_by('-data')[:1]
    return render(request, 'contato.html', {'form' : form, 'jogos' : jogos})

artilharia/views.py
from django.shortcuts import render, redirect
from jogos.models import Jogo

def artilharia(request):
    jogos = Jogo.objects.order_by('-data')[:1]
    return render(request, 'artilharia.html', {'jogos' : jogos})

atletas/views.py
from django.shortcuts import render, redirect
from .models import Atleta
from jogos.models import Jogo

def atletas(request):
    atletas = Atleta.objects.all()
    jogos = Jogo.objects.order_by('-data')[:1]
    return render(request, 'atletas.html', {'atletas' : atletas, 'jogos' : jogos})

def detalhes(request, slug):
    atleta = Atleta.objects.get(slug=slug)
    jogos = Jogo.objects.order_by('-data')[:1]
    return render(request, 'detalhe_atleta.html', {'atleta' : atleta, 'jogos' : jogos})

home/views.py
from django.shortcuts import render, redirect
from jogos.models import Jogo
from noticias.models import Noticia
from atletas.models import Atleta

def home(request):
    jogos = Jogo.objects.order_by('-data')[:1]
    noticias = Noticia.objects.order_by('-data')[:3]
    atletas = Atleta.objects.order_by('-nome')[:4]
    return render(request, 'home.html', {'jogos' : jogos, 'noticias' : noticias, 'atletas' : atletas})

jogos/views.py
from django.shortcuts import render, redirect
from .models import Jogo

def jogos(request):
    jogos = Jogo.objects.order_by('-data')[:1]
    lista_jogos = Jogo.objects.all()
    return render(request, 'jogos.html', {'jogos' : jogos, 'lista_jogos' : lista_jogos})

noticias/views.py
from django.shortcuts import render, redirect
from .models import Noticia
from jogos.models import Jogo

def noticias(request):
    noticias = Noticia.objects.all()
    jogos = Jogo.objects.order_by('-data')[:1]
    return render(request, 'noticias.html', {'noticias' : noticias, 'jogos' : jogos})

def detalhes(request, slug):
    noticia = Noticia.objects.get(slug=slug)
    jogos = Jogo.objects.order_by('-data')[:1]
    return render(request, 'detalhe_noticia.html', {'noticia' : noticia, 'jogos' : jogos})
    #return HttpResponse(slug)

artilharia/templates/artilharia.html
{% extends 'base.html' %}

{% block title %} Artilharia - Aldeota Clube | Melhor time de futebol amador de Fortaleza/CE {% endblock %}

{% block main %}
<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="section-heading text-uppercase">Artilharia</h2>
            </div>

            Em construção

        </div><!-- .row -->
    </div>
</section>
{% endblock %}

{% block atletas %}{% endblock %}

atletas/templates/atletas.html
{% extends 'base.html' %}

{% block title %} Atletas - Aldeota Clube | Melhor time de futebol amador de Fortaleza/CE {% endblock %}

{% block main %}
<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="section-heading text-uppercase">Atletas</h2>
            </div>
            {% for atleta in atletas %}
            <div class="info-noticia">

                <div class="info-atleta">
                    <a href="{% url 'atletas:detalhes' slug=atleta.slug %}">
                        <img src="{{ atleta.imagem.url }}" alt="{{ atleta.imagem }}">
                        <p>{{ atleta.nome }}{{ atleta.sobrenome }}</p>
                    </a>
                </div>
                <p class="info-data">{{ atleta.data }}</p>

                <div class="clear-noticias"></div>
            </div>
            {% endfor %}
        </div><!-- .row -->
    </div>
</section>
{% endblock %}

{% block atletas %}{% endblock %}

atletas/templates/detalhe_atleta.html
{% extends 'base.html' %}

{% block title %} Atletas - Aldeota Clube | Melhor time de futebol amador de Fortaleza/CE {% endblock %}

{% block main %}
<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="section-heading text-uppercase">Atletas</h2>
            </div>
            <div class="info-noticia">
                <img src="{{ atleta.imagem.url }}" alt="{{ atleta.imagem }}">
                <span>
                    <div class="info-title">
                        {{ atleta.nome }}{{ atleta.sobrenome }}</div><br />
                    <p class="info-data">{{ atleta.idade }}</p>
                    <p class="info-data">{{ atleta.data_nascimento }}</p>
                    <p class="info-data">{{ atleta.local_nascimento }}</p>
                    <p class="info-data">{{ atleta.apelido }}</p>
                </span>
                <div class="info-blog">
                    {{ atleta.descricao }}
                </div>
            </div>
        </div><!-- .row -->
    </div>
</section>
{% endblock %}

{% block atletas %}{% endblock %}

home/templates/home.html
{% extends 'base.html' %}

{% block title %} Aldeota Clube | Melhor time de futebol amador de Fortaleza/CE {% endblock %}

jogos/templates/jogos.html
{% extends 'base.html' %}

{% block title %} Jogos - Aldeota Clube | Melhor time de futebol amador de Fortaleza/CE {% endblock %}

{% block main %}
<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="section-heading text-uppercase">Jogos</h2>
            </div>
            {% for jogo in jogos %}
            <div class="info-noticia">
                <span>
                    <div class="info-title">
                        Aldeota x {{ jogo.adversario }}
                    </div><br />
                    <p class="info-data"><i class="fa fa-calendar"></i>&nbsp;{{ jogo.data }}</p>
                </span>
            </div>
            {% endfor %}
        </div><!-- .row -->
    </div>
</section>
{% endblock %}

{% block atletas %}{% endblock %}

noticias/templates/detalhe_noticia.html
{% extends 'base.html' %}

{% block title %} Notícias - Aldeota Clube | Melhor time de futebol amador de Fortaleza/CE {% endblock %}

{% block main %}
<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="section-heading text-uppercase">Notícias</h2>
            </div>
            <div class="info-noticia">
                <img src="{{ noticia.imagem.url }}" alt="{{ noticia.imagem }}">
                <span>
                    <div class="info-title">
                        {{ noticia.titulo }}</div><br />
                    <p class="info-data"><i class="fa fa-calendar"></i>&nbsp;{{ noticia.data }}</p>
                </span>
                <div class="info-blog">
                    {{ noticia.conteudo }}
                </div>
            </div>
        </div><!-- .row -->
    </div>
</section>
{% endblock %}

{% block atletas %}{% endblock %}

noticias/templates/detalhes.html
{% extends 'base.html' %}

{% block title %} Notícias - Aldeota Clube | Melhor time de futebol amador de Fortaleza/CE {% endblock %}

{% block main %}
<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="section-heading text-uppercase">Notícias</h2>
            </div>
            <div class="info-noticia">
                <img src="{{ noticia.imagem.url }}" alt="">
                <span>
                    <div class="info-title">
                        {{ noticia.titulo }}</div><br />
                    <p class="info-data"><i class="fa fa-calendar"></i>&nbsp;{{ noticia.data }}</p>
                </span>
                <div class="info-blog">
                    {{ noticia.conteudo }}
                </div>
            </div>
        </div><!-- .row -->
    </div>
</section>
{% endblock %}

noticias/templates/noticias.html
{% extends 'base.html' %}

{% block title %} Notícias - Aldeota Clube | Melhor time de futebol amador de Fortaleza/CE {% endblock %}

{% block main %}
<section id="blog">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2 class="section-heading text-uppercase">Notícias</h2>

                {% for noticia in noticias %}
                <div class="info-noticia">
                    <span>
                        <div class="info-title">
                            <a href="{% url 'noticias:detalhes' slug=noticia.slug %}">{{ noticia.titulo }}</a>
                        </div>
                        <br />
                        <p class="info-data"><i class="fa fa-calendar"></i>&nbsp;{{ noticia.data }}</p>
                    </span>
                    <div class="info-blog">
                        {{ noticia.snippet_noticia }}
                    </div>
                    <div class="clear-noticias"></div>
                </div>
                {% endfor %}

            </div>
        </div><!-- .row -->
    </div>
</section>
{% endblock %}

{% block atletas %}{% endblock %}

templates/base.html
{% load static %}

<! DOCTYPE HTML>
<html lang="pt-br" prefix="og: http://ogp.me/ns#">
<head>
	<meta charset="utf-8">
	<META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">

	<link rel="shortcut icon" href="{% static 'images/favicon-aldeota.jpg' %}" />

	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css"
  integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
  crossorigin=""/>

	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

	<title>{% block title %}{% endblock %}</title>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <meta property="og:title" content="Aldeota Clube"/>
    <meta property="og:description" content="Aldeota Clube - Time de Futebol amador de Fortaleza/CE" />
    <meta property="og:image" content="{% static 'images/logo-aldeota.png' %}"/>
    <meta property="og:url" content="http://www.aldeotaclube.com.br"/>

</head>

<body>
    
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll-trigger" href="{% url 'home' %}">
              <img src="{% static 'images/logo-aldeota.png' %}" alt="Aldeota Clube" width="100px" height="100px">
          </a>
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fa fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav text-uppercase ml-auto">
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'sobre' %}"><b>Sobre o time</b></a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'noticias:noticias' %}"><b>Notícias</b></a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'atletas:atletas' %}"><b>Atletas</b></a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'artilharia' %}"><b>Artilharia</b></a>
              </li>
              <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'contato' %}"><b>Contato</b></a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
  
	  <!-- Header -->
      <header class="masthead">
          <div class="container">
            <div class="intro-text">
              <div class="intro-lead-in">&nbsp;</div>
              <div class="intro-heading text-uppercase">&nbsp;</div>
              <br /><br />
            </div>
          </div>
      </header>

      <!-- Partida -->
      <div class="partida">
          <div class="container">
            {% for jogo in jogos %}
            <div class="row">
              <div class="col-md-3">
                  <img src="{% static 'images/logo-aldeota.png' %}" alt="" width="100px" height="100px"> X
                  {% if jogo.escudo_adversario %}
                      <img src="/media/{{ jogo.escudo_adversario }}" alt="" width="100px" height="100px">
                  {% else %}
                      <img src="{% static 'images/sem_escudo.png' %}" alt="" width="100px" height="100px">
                  {% endif %}
              </div>
              <div class="col-md-3 jogo">
                <span>
                  <b>Aldeota x {{ jogo.adversario }}</b>
                  <br />
                  <i class="fa fa-calendar"></i>&nbsp;
                  {{ jogo.data }}
                  <br />
                  <i class="fa fa-map-marker"></i>&nbsp;
                  {{ jogo.local }}
                  <br />
                  <i class="fa fa-gavel"></i>&nbsp;
                  {{ jogo.arbitragem }}
                </span>
              </div>
              <div class="col-md-3">
                  <br />
                  <a href="{% url 'jogos' %}">
                  <button type="button" class="btn btn-primary">Jogos Anteriores</button></a>
              </div>
            </div>
            {% endfor %}
          </div>
      </div>
      <!-- Partida -->

	  <!-- Notícias -->
	  {% block main %}
      <section id="services">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 text-center">
              <h2 class="section-heading text-uppercase">Notícias</h2>
            </div>
          </div>
          <div class="row text-center">
            {% for noticia in noticias %}
            <div class="col-md-4">
                {% if noticia.image %}
                    <img src="{{ noticia.imagem.url }}" alt="{{ noticia.imagem }}" width="300px" height="250px">
                {% else %}
                    <img src="{% static 'images/default.jpg' %}" alt="" width="300px" height="250px">
                {% endif %}
                <a href="{% url 'noticias:detalhes' slug=noticia.slug %}">
                    <h4 class="service-heading">{{ noticia.titulo }}</h4>
                </a>
                <p class="text-muted">{{ noticia.snippet }}</p>
            </div>
            {% endfor %}
          </div>
        </div>
	  </section>
	  {% endblock %}
  
	  <!-- Atletas -->
	  {% block atletas %}
      <section class="bg-light" id="portfolio">
        <div class="container">
          <div class="row">
            <div class="col-lg-12 text-center">
              <h2 class="section-heading text-uppercase">Atletas</h2>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div id="Carousel" class="carousel slide">
                <!-- Carousel items -->
                <div class="carousel-inner">
                    
                  <div class="carousel-item active">
                    <div class="row">
                    {% for atleta in atletas %}
                        <div class="col-md-3">
                            <a href="{% url 'atletas:detalhes' slug=atleta.slug %}" class="thumbnail">
                                <img src="{{ atleta.imagem.url }}" alt="atleta.imagem">
                            </a>
                        </div>
                    {% endfor %}
                    </div><!--.row-->
                  </div><!--.carousel-item-->

                </div><!--.carousel-inner-->


              </div><!--.Carousel-->

              <div class="vertodos"><a href="{% url 'atletas:atletas' %}">Ver todos os atletas</a></div>

            </div>
          </div> 
        </div>
      </section>
	  {% endblock %}

	  <!-- Patrocinadores -->
	  {% block clientes %}
      <section class="py-5">
        <div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<h2 class="section-heading text-uppercase">Patrocinadores</h2>
				</div>
			</div>
          	<div class="row">
				<div class="col-md-12 col-sm-6">
				<a href="#">
					<img class="img-fluid d-block mx-auto" src="{% static 'images/parceiros.jpg' %}" alt="">
				</a>
				</div>          
          	</div>
        </div>
	  </section>
	  {% endblock %}
    
	  <!-- Footer -->
	  {% block rodape %}
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <span class="copyright">Copyright &copy; <b>Aldeota Clube 2018</b></span>
            </div>
            <div class="col-md-4">
              <ul class="list-inline social-buttons">
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-twitter"></i>
                  </a>
                </li>
                <li class="list-inline-item">
                  <a href="#">
                    <i class="fa fa-facebook"></i>
                  </a>
                </li>
              </ul>
            </div>
            <div class="col-md-4">
              <ul class="list-inline quicklinks">
                <li class="list-inline-item">
                  Desenvolvido por <a href="http://wwww.eltonmelosantos.com.br" target="blank">Elton Santos</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
    </footer>
	{% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js"
  integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
  crossorigin=""></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</body>

templates/contato.html
{% extends 'base.html' %}

{% load bootstrap %}

{% block title %} Contato - Aldeota Clube | Melhor time de futebol amador de Fortaleza/CE {% endblock %}

{% block main %}
<section id="blog">
    <div class="container">
        <h2 class="section-heading text-uppercase">Contato</h2>
        <div class="row">

            <div class="col-lg-6">

                <form action="#">
                    {% csrf_token %}
                    {{ form|bootstrap }}
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>

            </div>

            <div class="col-lg-6">
                <div id="map"></div>
            </div>

        </div><!-- .row -->
    </div>
</section>
{% endblock %}

{% block atletas %}{% endblock %}

templates/sobre.html
{% extends 'base.html' %}

{% block title %} Sobre - Aldeota Clube | Melhor time de futebol amador de Fortaleza/CE {% endblock %}

{% block main %}
<section id="blog">
    <div class="container">
        <div class="row">

            <h2 class="section-heading text-uppercase">Sobre o Aldeota Clube</h2>

            <div class="info-blog">
            Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os
            embaralhou para fazer um livro de modelos de tipos. Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado. Se
            popularizou na década de 60, quando a Letraset lançou decalques contendo passagens de Lorem Ipsum, e mais recentemente quando passou a ser integrado a softwares de editoração eletrônica como Aldus PageMaker. Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado. Se popularizou na década de 60, quando a Letraset lançou decalques contendo passagens de Lorem Ipsum, e mais recentemente quando passou a ser integrado a softwares de editoração eletrônica como Aldus PageMaker. Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e de impressos, e vem sendo utilizado desde o século XVI, quando um impressor desconhecido pegou uma bandeja de tipos e os embaralhou para fazer um livro de modelos de tipos. Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado. Se popularizou na década de 60, quando a Letraset lançou decalques contendo passagens de Lorem Ipsum, e mais recentemente quando passou a ser integrado a softwares de editoração eletrônica como Aldus PageMaker.
            </div>
        </div>
    </div>
</section>
{% endblock %}

{% block atletas %}{% endblock %}